### ISSUE TITLE
ModuleNotFoundError: No module named 'yolox' ?? how can i resolve it ? please!

### ISSUE THREAD

**Issue by jcyhcs** [Megvii-BaseDetection/YOLOX#154]
hi,professor:

i test use cmd liks this:
python3 tools/demo.py image -n yolox_tiny -c ../weights/yolox_tiny.pth.tar --path ../assets/dog.jpg --conf 0.3 --nms 0.65 --tsize 640 --save_result

BUT! I GOT ERROR:
result     
Traceback (most recent call last):
  File "tools/demo.py", line 14, in <module>
    from yolox.data.data_augment import preproc
ModuleNotFoundError: No module named 'yolox'

OH, please tell me why?  help ,please!

**Comment by arianyambao** [comment]
Hi, @jcyhcs. May I ask if you were able to solve the issue? If yes, how?

I am currently experiencing the same problem: 
```
Traceback (most recent call last):
  File "tools/train.py", line 10, in <module>
    from yolox.core import Trainer, launch
ModuleNotFoundError: No module named 'yolox'
```

Thank you!

**Comment by arianyambao** [comment]
> Hi, @jcyhcs. May I ask if you were able to solve the issue? If yes, how?
> 
> I am currently experiencing the same problem:
> 
> ```
> Traceback (most recent call last):
>   File "tools/train.py", line 10, in <module>
>     from yolox.core import Trainer, launch
> ModuleNotFoundError: No module named 'yolox'
> ```
> 
> Thank you!

Was able to find a quick fix, I manually exported my work directory and ran the train script again (on Jupyter notebook):
```
!export PYTHONPATH="${PYTHONPATH}:/your/path/to/project/" && python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 32 --fp16 -o -c ../yolox_s.pth
```

Here's the actual line I have used:
```
!export PYTHONPATH="${PYTHONPATH}:/home/jupyter/tutorials/yolo_x_trial/YOLOX/" && python tools/train.py -f exps/example/yolox_voc/yolox_voc_s.py -d 1 -b 32 --fp16 -o -c ../yolox_s.pth
```

**Comment by tulbureandreit** [comment]
Hello,

I have the same problem when Trying to run the UniTrack demo.

Traceback (most recent call last):
  File "demo/mot_demo.py", line 27, in <module>
    from detector.YOLOX.tools.demo import Predictor
  File "/home/cesiro/Desktop/UniTrack/detector/YOLOX/tools/demo.py", line 14, in <module>
    from yolox.data.data_augment import preproc
ModuleNotFoundError: No module named 'yolox.data'


And it did not resolve itself with your fix. Any idea? @arianyambao

**Comment by KashaMalaga** [comment]
Same here @tulbureandreit @arianyambao 

python tools/demo.py video -n yolox-s -c .\weights\yolox_l.pth --path 0 --conf 0.25 --nms 0.45 --tsize 640                       
Traceback (most recent call last):
  File "C:\Users\kasha\Documents\GitHub\YOLOX\tools\demo.py", line 14, in <module>
    from yolox.data.data_augment import ValTransform
**ModuleNotFoundError: No module named 'yolox.data'**

**Comment by tulbureandreit** [comment]
@KashaMalaga hello,
I thiink you would find your solution here
https://github.com/Zhongdao/UniTrack/issues/12 

Also, please check your paths for everything you open when executing demo.py! And the files ( i had some missing files)

**Comment by Avnsx** [comment]
First of, please make sure you decide yourself for 1 version of CUDA, I am using 11.3 in this.
I fixed this and many other installation and compilation errors, by uninstalling and re-installing the following programs in the exact order

1. Clone the repo and unzip it
1. Install Virtual Studio **2019 Community** (https://visualstudio.microsoft.com/downloads/)
2. Download CUDA https://developer.nvidia.com/cuda-11.3.0-download-archive (I just did express installation)
3. Get https://docs.conda.io/en/latest/miniconda.html for your version of python
4. Change package installation path to pythons site-packages ``conda config --add pkgs_dirs "C:\Program Files\Python38\Lib\site-packages"``
5. Install pytorch with cuda enabled ``conda install pytorch torchvision cudatoolkit=11.3 -c pytorch``
6. Navigate conda to the download directory of yolox and type in:
				- ``pip install -r requirements.txt``
				- ``pip install pycocotools`` # this should get added to requirements.txt btw @
				- ``pip install -v -e .`` # or  python setup.py develop
7. Congratulations you fixed the error, now you'll be able to do run yolox as described in Quick Start > Demo (example: ``python tools/demo.py video -n yolox-s -c /path/to/your/yolox_s.pth --path /path/to/your/video --conf 0.25 --nms 0.45 --tsize 640 --save_result --device [cpu/gpu]
``)

A couple notices:
* You can at the time of writing this; not install above CUDA 11.3, because conda does not provide a higher version in sources to compile with pytorch
* You can not install a higher version of Virtual Studio 2019, because of incompability with CUDA (devs did not add support for MSVS22 yet)
* You can not simply uninstall conda, because it removes its CUDA compiled pytorch version and that in return breaks yolox. But I think you could most likely avoid this 

@KashaMalaga @arianyambao @jcyhcs

**Comment by jsing20** [comment]
![image](https://user-images.githubusercontent.com/110102506/181925408-507790d9-4067-430c-ad40-4f0389a5e3bc.png)

Getting this error while running

train.py

**Comment by manish33scss** [comment]
yeah i know its late but,  
add 
**import sys
sys.path.append("..")**
just before 
from yolox.data.data_augment (etc)
in _demo.py_, it'll work

**Comment by amitsas94** [comment]
@manish33scss I tried your solution but still not able to resolve

**Comment by guoqiang0148666** [comment]
> yeah i know its late but, add **import sys sys.path.append("..")** just before from yolox.data.data_augment (etc) in _demo.py_, it'll work

or using absolute path.

**Comment by happylusa-liu** [comment]
Adding the path of the current working directory solves the issue.
```python
import os
import sys
sys.path.append(os.getcwd())
```
