### ISSUE TITLE
COCODataset has no attribute 'cache' ?

### ISSUE THREAD

**Issue by mahnehsilla** [Megvii-BaseDetection/YOLOX#1622]
I did this steps:
1. clone repo in colab
2. try demo with the dog and the pretrained weigthts (runs fine)
3. Run the training command 
```
!python -m yolox.tools.train -n yolox-s -c /content/yolox_s.pth -d 1 -b 64 --fp16 -o --cache disk
```

But I get this error that I do not know what is it about:

```
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
Exception ignored in: <function CacheDataset.__del__ at 0x7fada7fe0040>
Traceback (most recent call last):
  File "/content/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 177, in __del__
    if self.cache and self.cache_type == "ram":
AttributeError: 'COCODataset' object has no attribute 'cache'
```

The same error happens with the coco 128 dataset provided in tutorial

Any ideas?

**Comment by MoreLyxixi** [comment]
I have the same problems, do you solve it?

**Comment by mahnehsilla** [comment]
No :-(

**Comment by FateScript** [comment]
Did you pull the latest branch? @mahnehsilla

**Comment by mahnehsilla** [comment]
@MoreLyxixi how did you generate the annotations? Script, roboflow...?

**Comment by mikel-brostrom** [comment]
Same issue here @FateScript

**Comment by mahnehsilla** [comment]
I observed that for datasets of one class only, there is sensitivity for the class specified in the custom config of your model. For example, using Roboflow COCO json file of 1 class only, but where they fill up a class "none" as well (the categories is length), when I run with 1 or 2 as classes, one works the other one doesnt.

So I think the bottleneck is in the **categories** field for COCO datasets. Maybe there is something else.

**Comment by FateScript** [comment]
If you are training a COCO dataset, YOLOX should work well.  I have checked it on main branch, here is the [code](https://github.com/Megvii-BaseDetection/YOLOX/blob/b3a80beea4d7f298dd8245e8fbac61be8a273c82/yolox/data/datasets/datasets_wrapper.py#L158).

If you are training your self-defined dataset, we support cache your data into memory to speed up your training process.  Plz try to follow this [doc](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/docs/cache.md).

If your issue is not solved, plz post a error log here, I will check it carefully. @mahnehsilla  @mikel-brostrom

**Comment by mahnehsilla** [comment]
Thank you @FateScript . I will include the full error soon, when I re train it.

> If you are training your self-defined dataset

I use own data but with the MS-COCO format, that shouldnt make any difference. Correct? The code still loads data plus MS-COCO annotations I assume.

My datasets are easy to test for example from Roboflow. [One example here](https://universe.roboflow.com/aps360-project-s3dto/stop-sign-edhre). 

Following the instructions in the readme, it seems that if you are using a custom dataset with MS-COCO format, you wouldnt really need to change more than the model configuration file anda dataset path, in my case I put it at `/custom/.../yolox-s.py` and I know it is being read correctly as the code logs the configuration when running it.

* Is this correct?

I will make a Colab Notebook available to others once I can really make it run.

**Comment by mahnehsilla** [comment]
## Some good news

1. One of the lines in the error reported in the issue is
> TypeError: '>=' not supported between instances of 'int' and 'NoneType

The dataset had `bbox: [None, None, None, None]` in two items out of 1K, I have no idea why.

2. Next I tried running it but still AP is terrible, goes to zero and never moves away from it. 

I found the error here as well, the **categories** field has 2 categories for some reason. One of which is useless, as I know that there is only one category in this Dataset. 

I removed both in **val** and **train** json files, got amazing results.

Now I can see the code detecting stuff!! But it is not that accurate so far, but will keep trying. Thanks for helping @FateScript

**Comment by mahnehsilla** [comment]
Observed another problem where the error was very similar to the above but the key line was and Out of Range for an index of an array, be sure that the arrays bbox are all length 4, even the background class (put `[0,0,0,0]` and "area":0), all the elements must have the area field as well as it is used by the program.

**Comment by yydc-0** [comment]
I can be sure that this is the problem with the dataset. After I rewrote the original json dataset in coco format, the error was resolved, but unfortunately, I didn't find the difference between the rewritten dataset and the previous dataset.

**Comment by advaitp** [comment]
Did anyone solve this I am getting this issue even when I run the coco128 dataset and my custom dataset in COCO format.In yolox_base.py I updated the path 

<img width="2244" height="600" alt="Image" src="https://github.com/user-attachments/assets/d4fd571f-623c-4aaf-9887-1dc50b6c344c" />

but still getting the same error 
Traceback (most recent call last):
  File "/YOLOX/yolox/data/datasets/datasets_wrapper.py", line 177, in __del__
    if self.cache and self.cache_type == "ram":
AttributeError: 'COCODataset' object has no attribute 'cache'

The COCO dataset has cache argument set as False default as well.Is there any updated branch where it is corrected or is there issue with my dataset format ?

**Comment by santi-mir** [comment]
It is hard for me to help bc Ive not used this project for years now.

You could open a new issue to get more visibility.

@advaitp
